package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * HerbListConnector generated by hbm2java
 */
public class HerbListConnector implements java.io.Serializable {

	private HerbListConnectorId id;
	private String amount;
	private String unit;

	public HerbListConnector() {
	}

	public HerbListConnector(HerbListConnectorId id, String amount, String unit) {
		this.id = id;
		this.amount = amount;
		this.unit = unit;
	}

	public HerbListConnectorId getId() {
		return this.id;
	}

	public void setId(HerbListConnectorId id) {
		this.id = id;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
