package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * HerbsSampleList generated by hbm2java
 */
public class HerbsSampleList implements java.io.Serializable {

	private Integer id;
	private String name;
	private String effects;
	private String howToMake;
	private String howToUse;

	public HerbsSampleList() {
	}

	public HerbsSampleList(String name) {
		this.name = name;
	}

	public HerbsSampleList(String name, String effects, String howToMake, String howToUse) {
		this.name = name;
		this.effects = effects;
		this.howToMake = howToMake;
		this.howToUse = howToUse;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEffects() {
		return this.effects;
	}

	public void setEffects(String effects) {
		this.effects = effects;
	}

	public String getHowToMake() {
		return this.howToMake;
	}

	public void setHowToMake(String howToMake) {
		this.howToMake = howToMake;
	}

	public String getHowToUse() {
		return this.howToUse;
	}

	public void setHowToUse(String howToUse) {
		this.howToUse = howToUse;
	}

}
