package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * HerbsArticleConnector generated by hbm2java
 */
public class HerbsArticleConnector implements java.io.Serializable {

	private HerbsArticleConnectorId id;

	public HerbsArticleConnector() {
	}

	public HerbsArticleConnector(HerbsArticleConnectorId id) {
		this.id = id;
	}

	public HerbsArticleConnectorId getId() {
		return this.id;
	}

	public void setId(HerbsArticleConnectorId id) {
		this.id = id;
	}

}
