package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Herbs generated by hbm2java
 */
public class Herbs implements java.io.Serializable {

	private Integer id;
	private String name;
	private String otherName;
	private String sciName;
	private String image;
	private String usedPart;
	private String elements;
	private String effects;
	private String currency;
	private String howTo;
	private int amount;
	private Double oriUnitPrice;
	private Date created;
	private Double saleUnitPrice;

	public Herbs() {
	}

	public Herbs(String name, int amount, Date created) {
		this.name = name;
		this.amount = amount;
		this.created = created;
	}

	public Herbs(String name, String otherName, String sciName, String image, String usedPart, String elements,
			String effects, String currency, String howTo, int amount, Double oriUnitPrice, Date created,
			Double saleUnitPrice) {
		this.name = name;
		this.otherName = otherName;
		this.sciName = sciName;
		this.image = image;
		this.usedPart = usedPart;
		this.elements = elements;
		this.effects = effects;
		this.currency = currency;
		this.howTo = howTo;
		this.amount = amount;
		this.oriUnitPrice = oriUnitPrice;
		this.created = created;
		this.saleUnitPrice = saleUnitPrice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOtherName() {
		return this.otherName;
	}

	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}

	public String getSciName() {
		return this.sciName;
	}

	public void setSciName(String sciName) {
		this.sciName = sciName;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getUsedPart() {
		return this.usedPart;
	}

	public void setUsedPart(String usedPart) {
		this.usedPart = usedPart;
	}

	public String getElements() {
		return this.elements;
	}

	public void setElements(String elements) {
		this.elements = elements;
	}

	public String getEffects() {
		return this.effects;
	}

	public void setEffects(String effects) {
		this.effects = effects;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getHowTo() {
		return this.howTo;
	}

	public void setHowTo(String howTo) {
		this.howTo = howTo;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Double getOriUnitPrice() {
		return this.oriUnitPrice;
	}

	public void setOriUnitPrice(Double oriUnitPrice) {
		this.oriUnitPrice = oriUnitPrice;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Double getSaleUnitPrice() {
		return this.saleUnitPrice;
	}

	public void setSaleUnitPrice(Double saleUnitPrice) {
		this.saleUnitPrice = saleUnitPrice;
	}

}
