package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * HerbListConnectorId generated by hbm2java
 */
public class HerbListConnectorId implements java.io.Serializable {

	private int herbId;
	private int listId;

	public HerbListConnectorId() {
	}

	public HerbListConnectorId(int herbId, int listId) {
		this.herbId = herbId;
		this.listId = listId;
	}

	public int getHerbId() {
		return this.herbId;
	}

	public void setHerbId(int herbId) {
		this.herbId = herbId;
	}

	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HerbListConnectorId))
			return false;
		HerbListConnectorId castOther = (HerbListConnectorId) other;

		return (this.getHerbId() == castOther.getHerbId()) && (this.getListId() == castOther.getListId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHerbId();
		result = 37 * result + this.getListId();
		return result;
	}

}
