package com.hiepthanh.model;
// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * HerbsArticleConnectorId generated by hbm2java
 */
public class HerbsArticleConnectorId implements java.io.Serializable {

	private int herbId;
	private int articleId;

	public HerbsArticleConnectorId() {
	}

	public HerbsArticleConnectorId(int herbId, int articleId) {
		this.herbId = herbId;
		this.articleId = articleId;
	}

	public int getHerbId() {
		return this.herbId;
	}

	public void setHerbId(int herbId) {
		this.herbId = herbId;
	}

	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HerbsArticleConnectorId))
			return false;
		HerbsArticleConnectorId castOther = (HerbsArticleConnectorId) other;

		return (this.getHerbId() == castOther.getHerbId()) && (this.getArticleId() == castOther.getArticleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHerbId();
		result = 37 * result + this.getArticleId();
		return result;
	}

}
