package com.hiepthanh.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

// Generated Dec 10, 2017 11:02:05 PM by Hibernate Tools 5.2.6.Final

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="Messages")
public class Messages implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	@Column(name="content")
	private String content;
	
	
	@ManyToOne( cascade = {CascadeType.MERGE})
    @JoinColumn(name="cust_id")
	private UserInfo user;

	
	
	public Messages() {
		super();
	}

	public Messages(int id) {
		super();
		this.id = id;
	}

	public Messages(int id, String content) {
		super();
		this.id = id;
		this.content = content;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public void setUser(UserInfo user) {
		this.user = user;
	}
	
	
	public UserInfo getUser() {
		return this.user;
	}


}
